[package]

name = "server"
version = "0.0.1"
authors = [ "Magnus Bergmark <magnus.bergmark@gmail.com>" ]

[dependencies.iron]
version = "*"

[dependencies.router]
version = "*"

[dependencies.time]
version = "0.1"
